CREATE DATABASE xss;
USE xss;

CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255), image VARCHAR(255));
CREATE TABLE messages(id INT PRIMARY KEY AUTO_INCREMENT, user INT, message VARCHAR(255), timestamp TIMESTAMP);